// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: in.proto

// Package in.v1 is the first version ...

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cmd_Type int32

const (
	Cmd_ENTER  Cmd_Type = 0
	Cmd_LISTEN Cmd_Type = 1
)

// Enum value maps for Cmd_Type.
var (
	Cmd_Type_name = map[int32]string{
		0: "ENTER",
		1: "LISTEN",
	}
	Cmd_Type_value = map[string]int32{
		"ENTER":  0,
		"LISTEN": 1,
	}
)

func (x Cmd_Type) Enum() *Cmd_Type {
	p := new(Cmd_Type)
	*p = x
	return p
}

func (x Cmd_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_in_proto_enumTypes[0].Descriptor()
}

func (Cmd_Type) Type() protoreflect.EnumType {
	return &file_in_proto_enumTypes[0]
}

func (x Cmd_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd_Type.Descriptor instead.
func (Cmd_Type) EnumDescriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{0, 0}
}

type CmdStatus_Type int32

const (
	CmdStatus_STATUS    CmdStatus_Type = 0
	CmdStatus_READY_OK  CmdStatus_Type = 1
	CmdStatus_READY_ERR CmdStatus_Type = 2
)

// Enum value maps for CmdStatus_Type.
var (
	CmdStatus_Type_name = map[int32]string{
		0: "STATUS",
		1: "READY_OK",
		2: "READY_ERR",
	}
	CmdStatus_Type_value = map[string]int32{
		"STATUS":    0,
		"READY_OK":  1,
		"READY_ERR": 2,
	}
)

func (x CmdStatus_Type) Enum() *CmdStatus_Type {
	p := new(CmdStatus_Type)
	*p = x
	return p
}

func (x CmdStatus_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdStatus_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_in_proto_enumTypes[1].Descriptor()
}

func (CmdStatus_Type) Type() protoreflect.EnumType {
	return &file_in_proto_enumTypes[1]
}

func (x CmdStatus_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdStatus_Type.Descriptor instead.
func (CmdStatus_Type) EnumDescriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{1, 0}
}

type Cmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     Cmd_Type `protobuf:"varint,1,opt,name=type,proto3,enum=in.v1.Cmd_Type" json:"type,omitempty"`
	UserName string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_in_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{0}
}

func (x *Cmd) GetType() Cmd_Type {
	if x != nil {
		return x.Type
	}
	return Cmd_ENTER
}

func (x *Cmd) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// CmdStatus is structure to return cmd statuses.
type CmdStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdID   int64          `protobuf:"varint,1,opt,name=cmdID,proto3" json:"cmdID,omitempty"`
	Type    CmdStatus_Type `protobuf:"varint,2,opt,name=type,proto3,enum=in.v1.CmdStatus_Type" json:"type,omitempty"`
	CmdType Cmd_Type       `protobuf:"varint,3,opt,name=cmd_type,json=cmdType,proto3,enum=in.v1.Cmd_Type" json:"cmd_type,omitempty"`
	// Types that are assignable to Info:
	//
	//	*CmdStatus_Ok
	//	*CmdStatus_Err
	Info isCmdStatus_Info `protobuf_oneof:"Info"`
}

func (x *CmdStatus) Reset() {
	*x = CmdStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStatus) ProtoMessage() {}

func (x *CmdStatus) ProtoReflect() protoreflect.Message {
	mi := &file_in_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStatus.ProtoReflect.Descriptor instead.
func (*CmdStatus) Descriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{1}
}

func (x *CmdStatus) GetCmdID() int64 {
	if x != nil {
		return x.CmdID
	}
	return 0
}

func (x *CmdStatus) GetType() CmdStatus_Type {
	if x != nil {
		return x.Type
	}
	return CmdStatus_STATUS
}

func (x *CmdStatus) GetCmdType() Cmd_Type {
	if x != nil {
		return x.CmdType
	}
	return Cmd_ENTER
}

func (m *CmdStatus) GetInfo() isCmdStatus_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (x *CmdStatus) GetOk() *CmdStatus_OKResult {
	if x, ok := x.GetInfo().(*CmdStatus_Ok); ok {
		return x.Ok
	}
	return nil
}

func (x *CmdStatus) GetErr() string {
	if x, ok := x.GetInfo().(*CmdStatus_Err); ok {
		return x.Err
	}
	return ""
}

type isCmdStatus_Info interface {
	isCmdStatus_Info()
}

type CmdStatus_Ok struct {
	Ok *CmdStatus_OKResult `protobuf:"bytes,4,opt,name=ok,proto3,oneof"`
}

type CmdStatus_Err struct {
	Err string `protobuf:"bytes,5,opt,name=err,proto3,oneof"`
}

func (*CmdStatus_Ok) isCmdStatus_Info() {}

func (*CmdStatus_Err) isCmdStatus_Info() {}

type CmdStatus_OKResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CmdStatus_OKResult) Reset() {
	*x = CmdStatus_OKResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdStatus_OKResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStatus_OKResult) ProtoMessage() {}

func (x *CmdStatus_OKResult) ProtoReflect() protoreflect.Message {
	mi := &file_in_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStatus_OKResult.ProtoReflect.Descriptor instead.
func (*CmdStatus_OKResult) Descriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CmdStatus_OKResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_in_proto protoreflect.FileDescriptor

var file_in_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x22, 0x65, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4c, 0x49, 0x53, 0x54, 0x45, 0x4e, 0x10, 0x01, 0x22, 0x92, 0x02, 0x0a, 0x09, 0x43, 0x6d, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6d, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x6d, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6d, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x4f, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x12, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x1a, 0x1e, 0x0a, 0x08, 0x4f, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f,
	0x45, 0x52, 0x52, 0x10, 0x02, 0x42, 0x06, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x66, 0x0a,
	0x09, 0x49, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x0a, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6d, 0x64, 0x1a, 0x10, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6d, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x08, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x43, 0x6d, 0x64, 0x12, 0x0a, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6d,
	0x64, 0x1a, 0x10, 0x2e, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6d, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x69, 0x6e, 0x69, 0x6f, 0x2f, 0x6e, 0x61, 0x74, 0x73, 0x2d,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_in_proto_rawDescOnce sync.Once
	file_in_proto_rawDescData = file_in_proto_rawDesc
)

func file_in_proto_rawDescGZIP() []byte {
	file_in_proto_rawDescOnce.Do(func() {
		file_in_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_proto_rawDescData)
	})
	return file_in_proto_rawDescData
}

var file_in_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_in_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_in_proto_goTypes = []interface{}{
	(Cmd_Type)(0),              // 0: in.v1.Cmd.Type
	(CmdStatus_Type)(0),        // 1: in.v1.CmdStatus.Type
	(*Cmd)(nil),                // 2: in.v1.Cmd
	(*CmdStatus)(nil),          // 3: in.v1.CmdStatus
	(*CmdStatus_OKResult)(nil), // 4: in.v1.CmdStatus.OKResult
}
var file_in_proto_depIdxs = []int32{
	0, // 0: in.v1.Cmd.type:type_name -> in.v1.Cmd.Type
	1, // 1: in.v1.CmdStatus.type:type_name -> in.v1.CmdStatus.Type
	0, // 2: in.v1.CmdStatus.cmd_type:type_name -> in.v1.Cmd.Type
	4, // 3: in.v1.CmdStatus.ok:type_name -> in.v1.CmdStatus.OKResult
	2, // 4: in.v1.InService.ListenCmd:input_type -> in.v1.Cmd
	2, // 5: in.v1.InService.EnterCmd:input_type -> in.v1.Cmd
	3, // 6: in.v1.InService.ListenCmd:output_type -> in.v1.CmdStatus
	3, // 7: in.v1.InService.EnterCmd:output_type -> in.v1.CmdStatus
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_in_proto_init() }
func file_in_proto_init() {
	if File_in_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_in_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdStatus_OKResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_in_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CmdStatus_Ok)(nil),
		(*CmdStatus_Err)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_in_proto_goTypes,
		DependencyIndexes: file_in_proto_depIdxs,
		EnumInfos:         file_in_proto_enumTypes,
		MessageInfos:      file_in_proto_msgTypes,
	}.Build()
	File_in_proto = out.File
	file_in_proto_rawDesc = nil
	file_in_proto_goTypes = nil
	file_in_proto_depIdxs = nil
}
